name: release
on:
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Maven Package
        run: mvn -B clean package -DskipTests

      - name: Maven Verify
        run: mvn -B clean verify

      - name: Release Maven package
        uses: samuelmeuli/action-maven-publish@v1
        with:
          server_id: central
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
          nexus_username: ${{ secrets.NEXUS_USERNAME }}
          nexus_password: ${{ secrets.NEXUS_PASSWORD }}

      - name: Create Release Message
        run: |
          echo "## What's changed?" > release.txt
          git fetch --tags --force
          git tag -l --sort=-taggerdate --format='%(contents)' $(git describe --tags $(git branch --show-current)) | grep . | while read line; do echo "- $line"; done >> release.txt

      - name: Release GitHub sources
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body_path: release.txt
          draft: false
          prerelease: false
